spring:

  #External application.yml location that replaced defaults
  config:
    location: ./

  #Connection to DB
  datasource:
    driver-class-name: org.hsqldb.jdbc.JDBCDriver
    url: jdbc:hsqldb:mem:test
    username: root
    password: root
  jpa:
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
    database-platform: org.hibernate.dialect.HSQLDialect

server:
  servlet:
    context-path: /api
  port: 8090
