spring:

  #External application.yml location that replaced defaults
  config:
    location: ./

  #Connection to DB
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost/test?autoReconnect=true
    username: root
    password: root
  jpa:
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
    database-platform: org.hibernate.dialect.MySQLDialect

server:
  servlet:
    context-path: /api
  port: 8080
